### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [pewaru-333/HomeMedkit-App#10]
Add material themed icon

**Comment by pewaru-333** [comment]
> Add material themed icon

Thank you.

Do you mean app icon?

**Comment by pewaru-333** [comment]
> @pewaru-333 when you're going to fix this issue

Thank you. App icon will be redesigned in 1.1.10.

**Comment by pewaru-333** [comment]
> @pewaru-333 when you're going to fix this issue

Will be added earlier, in 1.0.9. Created adaptive icon today. Wait a little bit more, please.

**Comment by pewaru-333** [comment]
Added in 1.0.9
