### ISSUE TITLE
what is android.permission.SYSTEM_ALERT_WINDOW needed for?

### ISSUE THREAD

**Issue by IzzySoft** [pewaru-333/HomeMedkit-App#11]
I just noticed HomeMedkit requests `android.permission.SYSTEM_ALERT_WINDOW`. From description or screenshots I cannot deduce why. Is this really needed – and if so, what for? Thanks in advance for clarification!

**Comment by pewaru-333** [comment]
Thank you.

When devices restarts, all alarms are cancelled. To reschedule alarm the app need to be invoked. I searched through Internet and found a way to do it — create toast message. But it can't be shown without that permission. 

I tested it on my device only unfortanutely. But I am going to find another way to do this soon, if there is one.

**Comment by IzzySoft** [comment]
I've never heard that toasts need this permission. [Their documentation](https://developer.android.com/guide/topics/ui/notifiers/toasts) doesn't mention *any* permission required. If rescheduling alarms would need that, a lot more applications (like pill reminders) would need it, and I haven't noticed that (yet).

Could it be you tested on Android 13? Maybe [this article](https://scribe.rip/@debuggingisfun/toasting-from-android-13-b3c45877ec1e) can help you? Quote:

> Notification permission introduced in Android 13 controls both notifications and background toasts. This impacts not just background application components like services, scheduled work but also widgets, as application processing widget logic is considered to be in background state.

If you really need a toast, that is. If it's just to reschedule alarms, maybe [this StackOverflow Q&A](https://stackoverflow.com/q/63293900/2533433) might be more helpful. Also see [this documentation](https://developer.android.com/develop/background-work/services/alarms/schedule) which includes re-scheduling.

**Comment by IzzySoft** [comment]
That's strange. Unfortunately I cannot give technical help with that, I'm no Android dev myself. Maybe raise a question on StackOverflow? You can do that even without registering an account there if you prefer (though in that case you would not receive any email notifications should someone answer – as without registration, the system would not know where to send them to).

**Comment by pewaru-333** [comment]
> That's strange. Unfortunately I cannot give technical help with that, I'm no Android dev myself. Maybe raise a question on StackOverflow? You can do that even without registering an account there if you prefer (though in that case you would not receive any email notifications should someone answer – as without registration, the system would not know where to send them to).

Thank you. I know that it is strange, will think what I can do.

**Comment by IzzySoft** [comment]
Thanks!

As you closed the issue: is the permission still there with the next release? Because then my scanner again will throw that warning. Not complaining, just want to know. Though I certainly will **get to know** then :see_no_evil:

**Comment by pewaru-333** [comment]
> Thanks!
> 
> As you closed the issue: is the permission still there with the next release? Because then my scanner again will throw that warning. Not complaining, just want to know. Though I certainly will **get to know** then 🙈

I have deleted this permission from the app manifest file in update 1.1.2, which was release here today

**Comment by IzzySoft** [comment]
Ah, cool – then that will become available here in less than an our. Update checker will start its run in 15 minutes. Thanks!
