### ISSUE TITLE
Fastlane changelogs too long

### ISSUE THREAD

**Issue by IzzySoft** [pewaru-333/HomeMedkit-App#14]
Fastlane limits per-release changelogs to 500 chars; everything beyond that is simply cut off (mid-word if that happens to be the position). Could you please make sure to stay within those limits?

```
ru.application.homemedkit/en-US/changelogs/17.txt has 539 chars
ru.application.homemedkit/ru/changelogs/17.txt has 574 chars
```

Thanks!

**Comment by pewaru-333** [comment]
Thank you. I will ensure it next time!

**Comment by IzzySoft** [comment]
Thanks!
