### ISSUE TITLE
Question on med API

### ISSUE THREAD

**Issue by IzzySoft** [pewaru-333/HomeMedkit-App#16]
The APK shows an API connected which is not found in the source code here:

![image](https://github.com/pewaru-333/HomeMedkit-App/assets/6781438/32f38d6c-9e23-4992-b221-3d639fafbc67)

Can you please clarify what API that is, and what data is sent there? Thanks in advance!

**Comment by pewaru-333** [comment]
Good evening. The sent data is decoded DataMatrix code (cis), there is only one POST request:

```java
public interface NetworkCall {

    @FormUrlEncoded
    @POST(BuildConfig.API_URL)
    Call<MainModel> requestInfo(@Field(CIS) String cis);
}
```


And the response is something like that:

```json
{
 "id": 247169092,
 "codeFounded": true,
 "checkResult": true,
 ...
 "prodFormNormName": "СПРЕЙ НАЗАЛЬНЫЙ ДОЗИРОВАННЫЙ",
 "prodDNormName": "84 мкг/доза + 70 мкг/доза",
 "prodPack1Name": "ФЛАКОН",
 "prodPack12": "1",
 "prodPack1Size": "60",
 ...
 "expireDate": 1793404800000,
 "images": "..."
}
```

**Comment by IzzySoft** [comment]
Thanks! Still wondering that the URL cannot be found in the code here (any reason for that?). And further, who runs that site, what their privacy policy is, and how user consent is handled. Is that site FOSS even? I could not find much about it, and my Russian is a bit "rusty" (insufficient to read tech/legal stuff, isveniy). So while I can *read* what's on their main site (`httpx://crpt.ru/`), I'm *far* from being able to comprehend it :see_no_evil:

**Comment by pewaru-333** [comment]
This information system is used to control the quality and safety of a quite big amount of goods. In my case we are interested in medicines. There is a mobile app from them (```https://chestnyznak.ru/en/```), where you can freely scan the DataMatrix code and findout information about product.

When app fetches data here (```https://mobile.api.crpt.ru/```) , only raw response comes back. I haven't detected any tracking or something like this.

Do I need to reveal API links in next update?

**Comment by IzzySoft** [comment]
As we're talking about open source here, it's a bit strange if pieces are missing. So when checking of the app was really built from this source, and pieces are missing (like the URL here), one won't succeed as the build can't be reproducible (see e.g. [Reproducible builds](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html)) – which is what made someone trying this suspicious so I was asked, as they found your app via my repo. Is there any reason to keep this "secret" and out of the source tree?

**Comment by pewaru-333** [comment]
For some reason I had and idea that all API links should be excluded from git source. 😢
I will fix this in next update. 👍
