### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [pewaru-333/HomeMedkit-App#17]
https://hosted.weblate.org/projects/homemedkit/android-strings/#information says
LGPLv3+
but https://github.com/pewaru-333/HomeMedkit-App?tab=GPL-3.0-1-ov-file#readme says
GPLv3+

can be changed in
https://hosted.weblate.org/settings/homemedkit/android-strings/ and
https://hosted.weblate.org/settings/homemedkit/glossary/

**Comment by pewaru-333** [comment]
Thank you, fixed.
