### ISSUE TITLE
Некорректное отображение иконок 

### ISSUE THREAD

**Issue by DanielD0101** [pewaru-333/HomeMedkit-App#19]
Некорректное отображение иконок на тёмной теме на нижней панели ![Screenshot_2024-05-07-16-11-06-91_801bd1f99e961627cf41c308da277954.jpg](https://github.com/pewaru-333/HomeMedkit-App/assets/71598935/d807089e-1574-4f2c-8bad-dbbc833d7562)

**Comment by pewaru-333** [comment]
Здравствуйте, спасибо, исправлено.
