### ISSUE TITLE
Home screen: Scanning button text is cut off 

### ISSUE THREAD

**Issue by uli-on** [pewaru-333/HomeMedkit-App#3]
On the Home screen, the text of the scanning button is cut off. For me it ends with "only for".

Fairphone FP3, 1080x2016, density 3x

**Comment by pewaru-333** [comment]
Thank you. Will be fixed in 1.0.3. Please, check this issue again and write here.

**Comment by uli-on** [comment]
I've just installed v1.03. The visible text amount hasn't changed, sorry. But I'm grateful for the change in text colour!

**Comment by pewaru-333** [comment]
> I've just installed v1.03. The visible text amount hasn't changed, sorry. But I'm grateful for the change in text colour!

Can you pin a screenshot, please? I checked various density types.

**Comment by uli-on** [comment]
Of course, but it's like I wrote, it's cut off after "only for". 

![Screenshot_20231126-160028](https://github.com/pewaru-333/HomeMedkit-App/assets/35634829/8c6d64d6-4837-4f4e-b02f-00f57a53fac4)

**Comment by pewaru-333** [comment]
Thank you. I triple checked device density and font scaling, surely will be fixed in 1.0.4

**Comment by uli-on** [comment]
> and font scaling

Ah, you're right, I'm also using a larger font-size than Android's default. Sorry, didn't think about that.

**Comment by uli-on** [comment]
This is fixed now, thank you!
