### ISSUE TITLE
Добавить возможность изменить дату начала периода приёма лекарства.

### ISSUE THREAD

**Issue by dmitry-w3b** [pewaru-333/HomeMedkit-App#30]
На данный момент в приложении нельзя гибко настроить приём лекарств. Я хотел-бы начать принимать Римантадин со следующего дня, но в приложении при нажатии на начальную дату ничего не происходит. Скриншот меню, о котором я имею в виду:
![Screenshot_20240914-173328_Аптечка~2](https://github.com/user-attachments/assets/f28054c8-cfd1-40cc-afd7-2a2b4ef48921)

**Comment by pewaru-333** [comment]
Здравствуйте. Вы можете отключить функцию упрощённого выбора периода приёма лекарств в настройках, а затем самостоятельно выбрать нужные начальные и конечные даты приёма.
