### ISSUE TITLE
Alarms and time adjustments

### ISSUE THREAD

**Issue by chrostino** [pewaru-333/HomeMedkit-App#37]
it would be a nice feature to be able to set the notification of medicines to take as an alarm and not just a normal notification for medicines of which the time to take them is very important. Also it would be a nice addition being able to change the time of taken medicines to keep track of when you have actually taken them (also in the case of medicines of which the time yoo take them is important)

**Comment by pewaru-333** [comment]
Hello. Can you explain this a little more clear: what do you mean "to set the notification of medicines to take as an alarm"? 
About second feature: I think I can add a field, where you can choose the fact time of intake. But not in a futher update, in 2-3 maybe.

**Comment by chrostino** [comment]
yes. So basically since with some medicines it's important to be punctual with the time to take them and normal notifications can be easily missed, I thought a good way to solve this problem is to be able to set for each medicine the mode to be notified by the app, either a normal app notification or an alarm like the one you have for the clock app to wake up.
Maybe a good solution to this problem could also be to be able to set a custom notification reminder x minutes/hours before the intended time to take the medicine that reminds you that you have a medicine to take some time after the notification, kinda like you can do in the calendar app that notifies you that you have an event in x days or in y hours

**Comment by pewaru-333** [comment]
Oh, I see. It would appear in a status bar like "You need to intake medicine _NAME_  at _TIME_", but before notification. I will think how I can achieve this, can't promise that it will be soon. Stay tuned for updates! :thumbsup:

**Comment by chrostino** [comment]
for sure👍

**Comment by pewaru-333** [comment]
@chrostino, good morning. These features added in 1.5.2 update. Please, contact back and close issue, if everything is OK.

**Comment by chrostino** [comment]
works like a charm
