### ISSUE TITLE
Невозможно ввести название и тп

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#45]
В полях ввода невозможно ввести текст - название, описание, дозарование и пр.

**Comment by hooddy** [comment]
Я наврал. Но у меня есть оправдание. При выборе поля ввода (тапе ра нем) ничего не происходит - не появляется курсор и не пропадает подсказка типа поля. Поэтому сложилось впечатление что ничего не вводится. Ожидаемое поведение - тапнул на поле - подсказка типа пропала и появился курсор. А так пока все мило. Картиночки особенно.

**Comment by pewaru-333** [comment]
> Ожидаемое поведение - тапнул на поле - подсказка типа пропала и появился курсор.

Возможно, что при тёмной теме курсор не очень заметен. Хотя, странно, на всех остальных полях цвет ближе к белому. Посмотрю, что можно сделать.
