### ISSUE TITLE
Прием капель или спреев

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#46]
Не могу понять, как выбрать капли или спрей в количестве. При занесении указывается объем, что правильно, но капаю я в глаза или пшикаю в нос или глотку не целый миллилитр, а каплю в глаз или дозу в нос. Ну и по спрею тоже объем может быть не в миллилитрах, а в дозах указан.

**Comment by pewaru-333** [comment]
Здравствуйте. Вы можете, например, изменить количество на "ЕД" в настройках лекарства, что сразу же отобразится в назначенном приёме. Либо посмотреть на коробке или в инструкции, какое количество лекарства в одной дозе ("пшыке"), а затем установить данное значение в настройках приёма.

**Comment by hooddy** [comment]
Для случая, когда указан общий объем в мл, а прием в каплях или пшикахм ваше решение так себе. Не пишут в прокламациях обьем одной капли или пшика. Не смертельно, конечно, но рушит картинку.

**Comment by pewaru-333** [comment]
@hooddy, напишите, какой вариант для дозы добавить — не вопрос. Просто можно вообще не указывать тип, тогда будет указано "Количество: 2".
