### ISSUE TITLE
Добавление БАДов через сканирование маркировки

### ISSUE THREAD

**Issue by authorless** [pewaru-333/HomeMedkit-App#47]
Здравствуйте, хотел попробовать добавить лекарство через qr Code, но так и не понял как это сделать правильно. Объясните пожалуйста

**Comment by pewaru-333** [comment]
Здравствуйте. Лекарство добавляется не по QR-коду, а по коду маркировки. Он выглядит примерно так.
![image](https://github.com/user-attachments/assets/83f7a397-0664-40f7-af33-4b9008c6dea6)

Функция работает только для лекарств, официально продаваемых в России.

**Comment by authorless** [comment]
А те маркировки которые на обратной стороне упаковки, это же они? Которые наклеены? Если да, то он их не может обработать почему-то. Просто не сканирует..

**Comment by pewaru-333** [comment]
@authorless, прикрепите сюда фотографию маркировку — разберёмся.

**Comment by authorless** [comment]
> @authorless, прикрепите сюда фотографию маркировку — разберёмся. 

![IMG_20241113_221617.jpg](https://github.com/user-attachments/assets/f9b023f5-2b20-4ce3-bf69-ce5205e781ce)

![IMG_20241113_221638.jpg](https://github.com/user-attachments/assets/5c98d7ca-c21c-48e6-a9df-a76c8e61e028)

**Comment by pewaru-333** [comment]
@authorless, понятно, это БАДы. Пока что их нельзя добавлять по маркировке, но в скором времени я такую функцию внедрю.

**Comment by authorless** [comment]
> @authorless, понятно, это БАДы. Пока что их нельзя добавлять по маркировке, но в скором времени я такую функцию внедрю.  

Вас понял, спасибо! Буду ждать обновление!

**Comment by pewaru-333** [comment]
@authorless, добавлено в обновлении 1.5.7. Переоткройте данную тему, если другие маркировки не будут сканироваться. Проверил на двух фото выше — работает.
