### ISSUE TITLE
Schedule setup: please add an option for "infinite" 

### ISSUE THREAD

**Issue by uli-on** [pewaru-333/HomeMedkit-App#5]
On setting up a reminder, there's no option for lifelong intake. Currently, we can only add single days in steps of one which is cumbersome and error prone when the set amount of days expires.

**Comment by uli-on** [comment]
I just discovered that I can use the number field like a normal numeric input field. So entering 999999 there would be an equivalent for lifelong. Hence maybe a standard numeric input is enough here.

**Comment by pewaru-333** [comment]
Thank you. Will be added in 1.0.3
