### ISSUE TITLE
Notifications don't last long enough

### ISSUE THREAD

**Issue by yamatt** [pewaru-333/HomeMedkit-App#52]
When a notification pops up to remind me about the medicine I need to take, it goes away after 10 minutes.

This is often not long enough.

Can the notification hang around until I have pressed a button or dismissed it?

**Comment by pewaru-333** [comment]
Hello. I had the discussion on this topic, opinions were divided. I think that this is optimal time if you need to take medicine right on time, but some people (and you) says that is not enough. I think I will increase this time to 20 (maybe 30) minutes, but not in next update I currently working on.

**Comment by yamatt** [comment]
Thanks for replying so fast. I totally understand.

For me, I need to take the medication with food, and 10 minutes just isn't enough time to cover it.

I know it's much more work, maybe it's something that could be configurable?

**Comment by pewaru-333** [comment]
> could be configurable

You mean that user input time? I think I will implement "picker" for it, but this is not priority feature. Maybe in 2-3 updates. I will leave this issue open until I will make it.

**Comment by meden** [comment]
> I think I will implement "picker" for it

Having the time configurable is certainly desirable, although possibly not the definitive solution.

Maybe, a first (easier) step could be the ability to configure the notification as persistent (I.e. they will disappear only upon user interaction).

No more risks to completely forget a pill. And it would make easier to track missed treatments.

**Comment by pewaru-333** [comment]
@meden, hello. Thank you for your suggestion. I will think about it. Next update won't be soon, but I think it will be rolled until the end of this year.

**Comment by pewaru-333** [comment]
Hello all. Add in 1.6.1 update. You can now select, either the notification won't be deleted until any user action, or it will be automatically cancelled after 10 minutes like before. Please, give your feedback!

**Comment by C4nnyKumqu4t** [comment]
Works great, thanks for implementing this! The hard-coded 10 min notification timeout was the only thing that kept me from using the app before. Happy new user since.
