### ISSUE TITLE
Improved Medication Planner

### ISSUE THREAD

**Issue by Korb** [pewaru-333/HomeMedkit-App#58]
Please consider adding regular events at a specified time with automatic reduction of the remaining amount of medication associated with the event. For example, to be able to add a notification like "from such and such a date to such and such a date at 8:00 and at 20:00 take these pills in the amount of 2 pcs.". I did not find such an option in the current interface of the application. If it exists, it needs to be implemented more obviously. Or add hints as QSG / tips on the corresponding screens.

Home Medkit 1.5.8 (43) f-droid (Dec 04, 2024)
OS version: Funtouch OS 14
Model: Vivo T1 (4G, V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.10.1.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
Kernel version: 4.19.157-perf+, 1 Fri Nov 15 11:50:50 CST 2024
Compile time: 15 Nov 2024 06:41:34
Android security update: 1 November 2024
Google Play system update: 1 October 2024
Software parameter update: 29 October 2024

**Comment by pewaru-333** [comment]
Hello. You can change interval and date range as you like (see screenshot).

![01](https://github.com/user-attachments/assets/879419f8-4a02-4faf-ad55-e747b2585455)

**Comment by Korb** [comment]
@pewaru-333, your screenshot shows a different set of fields than mine. In my case, the drug editing screen only contains the following fields:

- Product name
- Group
- Exp. date
- Description
- Dose
- Amount
- Indications for use
- Comment

Under what conditions do the following fields appear? —

- Quantity
- Left
- Interval
- Period
- Food & Med

**Comment by pewaru-333** [comment]
@Korb, you are describing medicine screen. You need to tap "Bell" icon on the top. I squared it at screenshot.

![03](https://github.com/user-attachments/assets/00a97d15-7aca-477c-b9cf-6d366ee3b06e)
