### ISSUE TITLE
Remove app language settings for >= Android 12

### ISSUE THREAD

**Issue by Korb** [pewaru-333/HomeMedkit-App#59]
The language selector in the app is kind of a legacy UI - now that Android supports per-app language settings (`System Settings` → `System` → `Languages` → `App languages`), we should support that and eventually get rid of the in-app language selector.

https://support.google.com/android/answer/12395118
https://developer.android.com/guide/topics/resources/app-languages
https://android-developers.googleblog.com/2022/11/per-app-language-preferences-part-1.html

**Comment by pewaru-333** [comment]
Hello. It is already implemented. 

![02](https://github.com/user-attachments/assets/757535ca-7541-42ba-acef-0d4ef26d6e34)

**Comment by pewaru-333** [comment]
It is fallback to < Android 12. Maybe I will hide this settings on devices, that have bigger version.

**Comment by Korb** [comment]
> It is fallback to < Android 12. Maybe I will hide this settings on devices, that have bigger version.

I have never seen before that the choice of interface language was simultaneously possible both through the application and through the system settings. If they do not conflict with each other, the question is removed. Please forgive me for my inattention.

**Comment by pewaru-333** [comment]
Added in 1.6.0 update.
