### ISSUE TITLE
WISH: Profiles Filter

### ISSUE THREAD

**Issue by zunami** [pewaru-333/HomeMedkit-App#68]
Hello!

I find your medication app very useful.
It would be great if you could offer an extension for families. You could create different profiles to manage medications for each person. The profiles would then be linked to the medications that each person is allowed to take. Quick access to the profiles directly on the home screen would be practical. This way, you could quickly switch between profiles and always only see the relevant medications. This feature would be especially helpful to avoid mix-ups for children, allergy sufferers, or people with other illnesses.

**Comment by pewaru-333** [comment]
Hello, thank you. App now has groups, where you can name them as relatives name. But notifications will pop up for any of group.
I think I will add the "Group" field to notification text soon.

**Comment by zunami** [comment]
Yes, I understand, but the problem is that I can only store a group once. There are medications that everyone can take and medications that only one person can take, so this type of filtering wouldn't work.

Or would I then have to store standard medications that everyone is allowed to take twice? that would be very inefficient.

**Comment by pewaru-333** [comment]
I understand. Is several groups (like checkboxes) for one medicine solution?

**Comment by zunami** [comment]
I do believe that this would be a solution, also from the point of view that the groups are also used for the storage location. Because the same medication can also be stored in two locations.

I just don't know how much programming is involved with profile filtering, but wouldn't that be a simpler solution?

**Comment by pewaru-333** [comment]
Added in 1.6.1 update. Now you can select several groups. Please, give your feedback!

**Comment by zunami** [comment]
Works very well
