### ISSUE TITLE
Question: What is the Comment field meant for? 

### ISSUE THREAD

**Issue by uli-on** [pewaru-333/HomeMedkit-App#7]
I don't quite understand the purpose of the "Comment" field, as it can only hold numbers, not comments.

**Comment by pewaru-333** [comment]
Thank you. It probably should be text. The idea was that you can write your notes (thoughts) for a medicine.

Will be fixed in 1.0.5.

**Comment by pewaru-333** [comment]
Fixed in 1.0.5

**Comment by uli-on** [comment]
Can you add text to the comments field? I cannot. The correct/alphab. keyboard opens, but my keypresses aren't reflected in the field.

**Comment by pewaru-333** [comment]
Thank you. This is strange, I will check this issue tomorrow.

**Comment by pewaru-333** [comment]
Will be fixed in 1.0.6

The issue was that I changed keyboard type, but forgot to remove accepted keys (numbers).

**Comment by pewaru-333** [comment]
Fixed in 1.0.6

**Comment by uli-on** [comment]
> Fixed in 1.0.6

Thank you :)
