### ISSUE TITLE
Уведомления не работают должным образом

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#70]
Совершенно неудовлетворен уведомлениями. Они пропадают. А должны висеть в шторке, пока я сам не тыкну на каждое с отметкой принял. Например я проспал и телефон в днд. Просыпаюсь - уведомлений нет, все препы приняты. Ровно тоже самое и в обычном режиме, если я был занят но не смахивал уведомления - они через какое-то время пропадают и препы типа приняты. Так быть не должно. Ну окм может я че не понимаю, но ни один другой трекер так себя не ведет. Это большое неудобство и я пока что ем кактус.

**Comment by pewaru-333** [comment]
Здравствуйте. Уведомления исчезают через 10 минут, если за это время вы не успели отреагировать, то у приёма статус остается "**Не принято**".

**Comment by hooddy** [comment]
Не понимаю и не могу согласится. Вот утренние улетели в принятые в режиме днд. Ранее и в обычном режиме я не понял почему уведомления пропали. Не должны они никуда автоматом улетать. Возможно у меня конкретно раьотает криво. Уведомление должно быть в шторке до его ручной обработки. Я в возрасте уже стремящемуся к склерозу и деменции, мне такая автоматика не нужна, если уведомление пропалоя могу либо забыть, что принял препы, либо не понять, куда оно делось и почему оно в прнятых (а оно в принятых).

**Comment by hooddy** [comment]
В обшем нет, не могу подтвердить. И в обычном режиме уведомления с которыми я не взаимодействовал и препы улетают в принятые.

**Comment by pewaru-333** [comment]
@hooddy, какой у вас смартфон (модель) и какое ПО производителя?

**Comment by hooddy** [comment]
я в иссю по количество таблов ответил. пожалуй все мои вопросы это снимает. но все равно по поводу 10 минутного лимита. сделайте опционально отключение (или наоборот включение) постоянных уведомлений, пока я вручную по ним не пройдусь (ну как любое другое системное уведомление, хоть смс. они же не пропадают, пока я не смахну их или не нажму на них или не очищу все оптом). это решит все текущие вопросы. 

тел так то с гуглом (с gappsами в смысле из коробки), но китайский unihertz titan (classic, большой самый).

**Comment by pewaru-333** [comment]
Возможно, что я добавлю пункт "Постоянное уведомление" в список дополнительных при настройке приёма.

**Comment by hooddy** [comment]
> Возможно, что я добавлю пункт "Постоянное уведомление" в список дополнительных при настройке приёма.

Будет удобно. Возможно с компоновкой всех уведомлений в одно, если такое допускается самой осью, хотя мне и так куча уведомлений не мешает. Повертье, когда вам будет под ~~сраку лет~~ полтос, вы оцените)

**Comment by pewaru-333** [comment]
@hooddy, здравствуйте. Забыл тут отписаться, что данная функция добавлена в обновлении 1.6.1. Если скомпоновать все уведомления в одно, то тогда для самого последнего можно будет установить статус, а для остальных он автотически примет значение "Не принято".

**Comment by hooddy** [comment]
обнолвился до текущей актуальной 1.6.2 но уведомления все арвно пропадают сами.

**Comment by hooddy** [comment]
И все таки нет. Я не могу у таблов которым снял 10 минутный лимит на уведомления ничего сделать - ни в шторке нажать принял, ни в приложении.

**Comment by pewaru-333** [comment]
@hooddy, нажмите на значок "Стрелочки вниз" в правом верхнем углу у уведомления. У вас много уведомлений в шторке, поэтому они автоматически сворачиваются. И ещё, измените язык с системного на английский в вашем случае, а то у вас формат даты странный какой-то.

**Comment by hooddy** [comment]
У меня английский язык в системе. Уведомлений ровно три штуки. Разве это много?

**Comment by pewaru-333** [comment]
@hooddy, так это не я решил, что уведомлений много, а ПО системы. Язык по умолчанию системный, на нескольких устройствах проверил — русский.

**Comment by hooddy** [comment]
> @hooddy, так это не я решил, что уведомлений много, а ПО системы. Язык по умолчанию системный, на нескольких устройствах проверил — русский.

Ок по шторке наверное да. Но все же вопрос, почему если в шторке не смахнул, то в приложке не дает отметить прием? Это не айс.

По языку вечером гляну у родни.

**Comment by pewaru-333** [comment]
Потому, что тогда можно будет случайно два раза "принять" лекарство.

**Comment by hooddy** [comment]
Ну в общем подтверждаю родню - на хуавее мейт 40 при русском системном интерфейса в аптечке английский вместо русского если стоит выбор системного.

**Comment by hooddy** [comment]
Как? Если в шторке выбрать принять, то в приложке статус меняется. А наоборот разве не работает (изменить статус на принято в приложке и в шторке уведомление должно пропасть, так ожидаю от программы). 
> Потому, что тогда можно будет случайно два раза "принять" лекарство.

**Comment by pewaru-333** [comment]
Эта часть пока не проработана, были какие-то сложности и несостыковки.

**Comment by hooddy** [comment]
> Эта часть пока не проработана, были какие-то сложности и несостыковки.

Ну надеюсь допилите. Вроде критических замечаний особо нет больше. Ну и язык посмотрите. Думаю странная дата и у меня в случае системного тоже результат этого бага.
