### ISSUE TITLE
Зачем в принятых общее количество препов?

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#71]
Я не понимаю, зачем из инфы по препу перекидывать инфу по количеству препов в упаковке, если не отнимать от нее принятую дозу. Потому что первое впечатление было именно такое, что я указываю дозу, но смотрю что тут же и общее количество указано, и думаю, что оно будет уменьшаться. Но нет. Это странно. А было бы удобно. Тогда для препов можно не указывать даты приемам а по истечении всего количества просто понятно, что преп закончился и можно прекратить его принимать, если речь о курсе приема, либо докупить и т.д.

**Comment by pewaru-333** [comment]
Здравствуйте. Количество лекарства отнимается автоматически после приёма и отображается в настройке его графика.

**Comment by hooddy** [comment]
Не понимаю. Да именно такое поведение и ожидаю. Но как было 60 к примеру, так и 60. Что я делаю не так?

**Comment by hooddy** [comment]
Нет, количество препов не уменьшается. Может быть я использую приложку как-то не так, но факт иостается фактом.

**Comment by hooddy** [comment]
обже, я понял. но не потому, что я тупой. интерфейс как то не слишком интуитивный. вкладка называется taken (принятые наверное по-русски), но чтобы отметить преп принятым, надо во вкладке принятые нажать на пропущенный прием (оказывается он пропущен во вкладке принятые!) и нажать на принят. ну блин...
