### ISSUE TITLE
Нет возможности редактировать название препа после скана

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#72]
Собственно, сабж. Скан это и правда удобно. Но мне совершенно не нужно в названии препа что-то вроде "БАД "Компливит(R) Магний". Я хочу иметь возможность просто назвать его компливит или вообще витаминка.

**Comment by pewaru-333** [comment]
Здравствуйте. Для отсканированных препаратов нельзя редактировать основные параметры. Возможно, что я добавлю "алиас" для отображения в списке всех лекарств, но это поле точно останется нередактируемым.

**Comment by hooddy** [comment]
Это плохо.

**Comment by pewaru-333** [comment]
Добавлено в обновлении 1.6.1. Теперь для любого лекарства можно настроить его отображаемое имя.
