### ISSUE TITLE
Нет возможности изменить сортировку принятых

### ISSUE THREAD

**Issue by hooddy** [pewaru-333/HomeMedkit-App#73]
Будет удобно менять сортировку с нисходящего на восходящий и наоборот. Мне удобнно, чтобы оно сверху сортировалось, а не снизу.

**Comment by pewaru-333** [comment]
Здравствуйте. Подумаю на этим предложением.

**Comment by hooddy** [comment]
сюда же добавлю возможность очистки вкладки принятые каким-либо образом. например после окончания препарата мне не надо тут простыню из приемов, особенно когда ее приходится мотать снизу вверх (мне правда кажется логичнее, если лог (да масло масляное) будет начинаться сверху, а не снизу. хотя здесь соглашусь, что взяли как раз из системного ui, те же смс тоже снизу вверх идут).

**Comment by pewaru-333** [comment]
Добавлено в обновлении 1.6.1. Значок — это временное решение, чуть позже он будет заменён.
