### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by johnjohndoe** [pewaru-333/HomeMedkit-App#9]
Do you plan to provide the app in other languages such as English or German? Do you accept translation contributions? Do you use an external translation management tool?

**Comment by pewaru-333** [comment]
Thank you.

1. English is already available in the application;
2. This is planned in the near future;
3. I used knowledge of a foreign language for translation.

**Comment by johnjohndoe** [comment]
Thank you. I will have a look. Then the issue can be closed.
